import Providers from "@/providers/Providers";
import type { Metadata, Viewport } from "next";
import { Roboto } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Akaba Doors",
  description: "Generated by AkabaDoors",
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Toaster
            richColors
            position="top-center"
            toastOptions={{
              duration: 3000,
            }}
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
